# GitHub Release configuration
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🍭 Lollipop System Enhancements
      labels:
        - gamification
        - lollipops
        - enhancement
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔒 Security
      labels:
        - security
        - vulnerability
    - title: ⬆️ Dependencies
      labels:
        - dependencies
        - deps